<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <PublishSingleFile>true</PublishSingleFile>
    <IncludeNativeLibrariesForSelfExtract>false</IncludeNativeLibrariesForSelfExtract>
    <SelfContained>false</SelfContained>
    <EnableDynamicLoading>true</EnableDynamicLoading>
    <Version>1.0.1</Version>
    <AssemblyVersion>1.0.1</AssemblyVersion>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Grpc.Net.Client" Version="2.59.0" />
    <PackageReference Include="Microsoft.Extensions.DependencyInjection" Version="8.0.0" />
    <PackageReference Include="Microsoft.Extensions.DependencyInjection.Abstractions" Version="8.0.0" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\ExtensionEngine.Core.Proto\ExtensionEngine.Core.Proto.csproj" />
    <ProjectReference Include="..\ExtensionEngine.Plugin.Abstractions\ExtensionEngine.Abstractions.csproj" />
  </ItemGroup>

</Project>
