syntax = "proto3";
 
option csharp_namespace = "ExtensionEngine.Core.Proto";

package ExtensionEngine;

service ExtensionEngineFacade {
  rpc GetValidPluginVersions (GetValidPluginVersionsRequest) returns (GetValidPluginVersionsResponse);
  rpc SetValidPluginVersions (SetValidPluginVersionsRequest) returns (SetValidPluginVersionsResponse);
  rpc LoadPlugins (LoadPluginsRequest) returns (LoadPluginsResponse);
}
 
message GetValidPluginVersionsRequest {
  string host_id = 1;
}
 
message GetValidPluginVersionsResponse {
  repeated PluginMetadata metadata = 1;
}

message SetValidPluginVersionsRequest {
  string host_id = 1;
  PluginMetadata plugin_metadata = 2;
}

message SetValidPluginVersionsResponse {
}

message LoadPluginsRequest {
  repeated PluginMetadata metadata = 1;
}
 
message LoadPluginsResponse {
  repeated PluginContainer container = 1;
}

message PluginMetadata {
	string version = 1;
	string name = 2;
}

message PluginContainer {
	string data = 1;
	PluginMetadata metadata = 2;
}
