syntax = "proto3";
 
option csharp_namespace = "PluginManagement.Proto";

package PluginManagementFacadePackage;

service PluginManagementFacade {
  rpc GetValidPluginVersions (GetValidPluginVersionsRequest) returns (GetValidPluginVersionsResponse);
  rpc SetValidPluginVersions (SetValidPluginVersionsRequest) returns (SetValidPluginVersionsResponse);
  rpc LoadPlugins (LoadPluginsRequest) returns (LoadPluginsResponse);
}
 
message GetValidPluginVersionsRequest {
	string host_id = 1;
}
 
message GetValidPluginVersionsResponse {
	repeated PluginInfo plugin_info = 1;
}

message SetValidPluginVersionsRequest {
	string host_id = 1;
	PluginInfo plugin_info = 2;
}

message SetValidPluginVersionsResponse {
}

message LoadPluginsRequest {
	repeated PluginInfo plugin_info = 1;
}
 
message LoadPluginsResponse {
	repeated PluginContainer container = 1;
}

message PluginContainer {
	string data = 1;
	PluginInfo plugin_info = 2;
}

message PluginInfo {
	string version = 1;
	string name = 2;
}
