syntax = "proto3";
 
option csharp_namespace = "PluginGateway.Proto";

import "google/protobuf/timestamp.proto";

package PluginGatewayPackage;

service PluginGatewayFacade {
    rpc Publish(PublishRequest) returns (PublishResponse);
    rpc Send(SendRequest) returns (SendResponse);
    rpc Consume(ConsumeRequest) returns (ConsumeResponse);
    rpc Ack(AckRequest) returns (AckResponse);
}
 
message PublishRequest {
    HostInfo host_info = 1;
    PluginInfo plugin_info = 2;
    repeated EnvelopeMessage messages = 3;
}

message PublishResponse {
    repeated EnvelopeMessage messages = 1;
}

message SendRequest {
    HostInfo host_info = 1;
    PluginInfo plugin_info = 2;
    EnvelopeMessage messages = 3;
}

message SendResponse{
    EnvelopeMessage messages = 3;
}

message ConsumeRequest{
    HostInfo host_info = 1;
    PluginInfo plugin_info = 2;
    repeated EnvelopeMessage messages = 3;
}

message ConsumeResponse{
    repeated EnvelopeMessage messages = 3;
}

message AckRequest{
    HostInfo host_info = 1;
    PluginInfo plugin_info = 2;
    repeated EnvelopeMessage messages = 3;
}

message AckResponse{
    repeated EnvelopeMessage messages = 1;
}

message EnvelopeMessage {
    Payload payload = 1;
}

message Payload {
  string payload_type  = 1;
  string data = 2;
}

message HostInfo {
    string name = 1;
}

message PluginInfo {
	string version = 1;
	string name = 2;
}
